pipeline{
    agent any
    tools{
        jdk 'jdk'
        nodejs 'nodejs'
    }
    environment {
        SCANNER_HOME=tool 'sonar-server'
    }
    stages {
        stage('Workspace Cleaning'){
            steps{
                cleanWs()
            }
        }
    
        stage('Checkout from Git'){
            steps{
                git branch: 'main', url: 'https://github.com/Nattanan-Doangjinda/Netflix-Clone.git'
            }
        }
        stage("Sonarqube Analysis"){
            steps{
                withSonarQubeEnv('sonar-server') {
                    sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=Netflix \
                    -Dsonar.projectKey=Netflix \
                    '''
                }
            }
        }
        stage("Quality Gate"){
           steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token' 
                }
            } 
        }
        
        stage('Install Dependencies') {
            steps {
                dir('Application-Code') {
                    sh "npm install" 
                }
            }
        }
        
        stage('OWASP DP SCAN') {
            steps {
                dir('Application-Code') {
                    dependencyCheck additionalArguments: '--scan ./ --exclude "node_modules/**" --disableYarnAudit --disableNodeAudit', odcInstallation: 'owasp-dp-check'
                    dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
                }
            }
        }
        
        stage('TRIVY FS SCAN') {
            steps {
                sh "trivy fs . > trivyfs.txt"
            }
        }
        
        stage('Docker Build & Push') {
            steps {
                script {
                    dir('Application-Code'){
                        withDockerRegistry(credentialsId: 'docker') {
                            sh "docker build --build-arg TMDB_V3_API_KEY=6c92ff51abccd904f6c5b897946dea9 -t netflix ."
                            sh "docker tag netflix noppakron/netflix:latest"
                            sh "docker push noppakron/netflix:latest"
                        } 
                    }
                }
            }
        }
        
        stage('TRIVY Image Scan') {
            steps {
                sh "trivy image noppakron/netflix:latest > trivyimage.txt"
            }
        }
        
        stage('Deploy to Kubernetes'){
            steps{
                script{
                    dir('Kubernetes') {
                        withKubeConfig(credentialsId: 'k8s') {
                            sh 'kubectl apply -f deployment.yml'
                            sh 'kubectl apply -f service.yml'
                            sh 'kubectl rollout restart deployment/netflix-app'
                            sh 'kubectl get svc'
                            sh 'kubectl get all'
                        }
                    }
                }
            }
        }
    }
    post {
     always {
        emailext attachLog: true,
            subject: "'${currentBuild.result}'",
            body: "Project: ${env.JOB_NAME}<br/>" +
                "Build Number: ${env.BUILD_NUMBER}<br/>" +
                "URL: ${env.BUILD_URL}<br/>",
            to: 'netflixcloneproject01@gmail.com',
            attachmentsPattern: 'trivyfs.txt,trivyimage.txt'
        }
    }
}